server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name PAGE_SERVER;
    http2 on;
    server_tokens off;

    ssl_certificate      PATH_TO_HYS_CER;
    ssl_certificate_key  PATH_TO_HYS_KEY;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;

    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options    nosniff always;
    add_header X-Frame-Options           DENY always;
    add_header Referrer-Policy           no-referrer always;

    location ~* ^/(\.git|\.env|wp-admin|phpmyadmin|admin|config) {
        return 444;
    }

    if ($request_method !~ ^(GET|POST|HEAD)$) {
        return 444;
    }

    location / {
        root PATH_TO_HYS_WEB;
        try_files /index.html =404;
    }

    error_page 404 /index.html;
    error_page 500 502 503 504 /index.html;
}
